apiVersion: apps/v1
kind: Deployment
metadata:
    name: zevon-weather-deployment
    labels:
        app: zevon-weather-frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: zevon-weather-frontend
    template:
        metadata:
            labels:
                app: zevon-weather-frontend
        spec:
            containers:
                - name: zevon-weather
                  image: kanerix/zevon-weather:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
                  resources:
                      limits:
                          memory: 2048Mi
                          cpu: '2'
