name: Docker Image CI

on:
    push:
        branches:
            - 'main'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Make envfile
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  envkey_NODE_ENV: production
                  envkey_TOKEN_PASSWORD: ${{ secrets.TOKEN_PASSWORD }}
                  envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  file_name: .env
                  fail_on_empty: true

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: kanerix/zevon-weather:latest
